/**
 * export-rgt.js
 *
 * Emits the equivalent gt pipeline in R.
 *
 * The spec was designed to mirror gt's own decomposition, so this is close to a
 * direct transcription: each section becomes the call it was modelled on. That
 * is the point of the format — a table designed in the GUI can go straight into
 * a Quarto or R Markdown document and stay reproducible there.
 */

const ExportRgt = {

  /** Above this, the data is referenced rather than inlined. */
  MAX_INLINE_ROWS: 300,

  /**
   * @param {Object} spec
   * @param {Object} model - the resolved model, for derived values
   * @returns {string} R source
   */
  build(spec, model) {
    const out = [];
    const working = Reshape.derive(spec.source, spec.reshape);

    out.push('# Generated by Table Builder');
    out.push('# ' + new Date().toISOString().slice(0, 10));
    out.push('');
    out.push('library(gt)');
    out.push('library(dplyr)');
    out.push('');

    out.push.apply(out, ExportRgt.data(spec, working));
    out.push('');

    const pipeline = ExportRgt.pipeline(spec, model, working);
    out.push('tbl <- data |>');
    out.push(pipeline.map((line, i) => '  ' + line + (i < pipeline.length - 1 ? ' |>' : '')).join('\n'));
    out.push('');
    out.push('tbl');
    out.push('');
    out.push('# gtsave(tbl, "table.html")');
    out.push('# gtsave(tbl, "table.png", expand = 10)');
    out.push('');

    return out.join('\n');
  },

  /* ================================================================
     Data
     ================================================================ */

  data(spec, working) {
    const out = [];

    if (spec.reshape.mode === 'pivot') {
      out.push('# This table was built from a long file pivoted wider. The pivoted');
      out.push('# result is inlined below; the tidyr equivalent of that step is:');
      out.push('#   tidyr::pivot_wider(');
      out.push('#     id_cols = c(' + spec.reshape.idCols.map(ExportRgt.name).join(', ') + '),');
      out.push('#     names_from = c(' + spec.reshape.nameCols.map(ExportRgt.name).join(', ') + '),');
      out.push('#     values_from = c(' + spec.reshape.valueCols.map(ExportRgt.name).join(', ') + ')');
      out.push('#   )');
      out.push('');
    }

    if (working.rows.length > ExportRgt.MAX_INLINE_ROWS) {
      out.push('# ' + working.rows.length + ' rows is too many to inline readably.');
      out.push('# Point this at your own file — the column names below are what the');
      out.push('# rest of the pipeline expects.');
      out.push('# Columns: ' + working.columns.map((c) => c.id).join(', '));
      out.push('data <- readr::read_csv("' + (spec.source.filename || 'data.csv') + '")');
      return out;
    }

    out.push('data <- tibble::tribble(');
    out.push('  ' + working.columns.map((col) => '~' + ExportRgt.symbol(col.id)).join(', ') + ',');

    working.rows.forEach((row, index) => {
      const values = working.columns.map((col) => ExportRgt.value(row[col.id], col.type));
      out.push('  ' + values.join(', ') + (index < working.rows.length - 1 ? ',' : ''));
    });

    out.push(')');
    return out;
  },

  /* ================================================================
     Pipeline
     ================================================================ */

  pipeline(spec, model, working) {
    const st = spec.structure;
    const lines = [];
    const columnsById = {};
    for (const col of working.columns) columnsById[col.id] = col;

    /* ---- gt() ---- */

    const gtArgs = [];
    if (st.rownameCol) gtArgs.push('rowname_col = ' + ExportRgt.name(st.rownameCol));
    if (st.groupnameCol) gtArgs.push('groupname_col = ' + ExportRgt.name(st.groupnameCol));
    lines.push('gt(' + gtArgs.join(', ') + ')');

    /* ---- Header ---- */

    if (spec.parts.title || spec.parts.subtitle) {
      const args = [];
      if (spec.parts.title) args.push('title = ' + ExportRgt.md(spec.parts.title));
      if (spec.parts.subtitle) args.push('subtitle = ' + ExportRgt.md(spec.parts.subtitle));
      lines.push('tab_header(' + args.join(', ') + ')');
    }

    if (spec.parts.stubhead) {
      lines.push('tab_stubhead(label = ' + ExportRgt.md(spec.parts.stubhead) + ')');
    }
    if (spec.parts.caption) {
      lines.push('tab_caption(caption = ' + ExportRgt.md(spec.parts.caption) + ')');
    }

    /* ---- Columns ---- */

    // The stub and group columns are consumed by gt() itself and are no longer
    // addressable as ordinary columns, so they stay out of every cols_* call.
    const consumed = new Set([st.rownameCol, st.groupnameCol].filter(Boolean));

    const hidden = st.hidden.filter((id) => columnsById[id] && !consumed.has(id));
    if (hidden.length) {
      lines.push('cols_hide(columns = ' + ExportRgt.columnVector(hidden) + ')');
    }

    const visible = st.columnOrder.filter((id) =>
      columnsById[id] && !consumed.has(id) && hidden.indexOf(id) < 0);
    if (visible.length > 1) {
      lines.push('cols_move_to_start(columns = ' + ExportRgt.columnVector(visible) + ')');
    }

    // The emitted tibble is named by column *id*, so that is what gt will use
    // as a label unless told otherwise. Anything the GUI shows differently has
    // to be emitted — including the humanised defaults, or the R table would
    // read `mean_age` where the preview reads "Mean age".
    const labels = [];
    for (const id of visible) {
      const label = st.labels[id];
      if (label === undefined || label === id) continue;
      labels.push(ExportRgt.symbol(id) + ' = ' + ExportRgt.md(label));
    }
    if (labels.length) lines.push('cols_label(' + labels.join(', ') + ')');

    const alignGroups = Util.groupBy(
      visible.filter((id) => st.align[id] && st.align[id] !== 'auto'),
      (id) => st.align[id]
    );
    for (const [align, ids] of alignGroups) {
      lines.push('cols_align(align = "' + align + '", columns = ' + ExportRgt.columnVector(ids) + ')');
    }

    const widths = Object.keys(st.widths)
      .filter((id) => columnsById[id] && st.widths[id] && !consumed.has(id));
    if (widths.length) {
      lines.push('cols_width(' + widths.map((id) =>
        ExportRgt.symbol(id) + ' ~ ' + ExportRgt.width(st.widths[id])).join(', ') + ')');
    }

    /* ---- Spanners ---- */

    // Innermost first, so gt stacks them the way the preview shows them.
    const spanners = st.spanners.slice().sort((a, b) => (a.level || 1) - (b.level || 1));
    for (const spanner of spanners) {
      const cols = spanner.columns.filter((id) => columnsById[id]);
      if (!cols.length) continue;
      lines.push('tab_spanner(label = ' + ExportRgt.md(spanner.label) +
        ', columns = ' + ExportRgt.columnVector(cols) + ')');
    }

    /* ---- Merges ---- */

    for (const merge of st.merges) {
      if (!columnsById[merge.target]) continue;
      const others = merge.columns.filter((id) => columnsById[id]);
      if (!others.length) continue;
      const all = ExportRgt.columnVector([merge.target].concat(others));

      switch (merge.type) {
        case 'uncert':
          lines.push('cols_merge_uncert(col_val = ' + ExportRgt.name(merge.target) +
            ', col_uncert = ' + ExportRgt.name(others[0]) + ')');
          break;
        case 'range':
          lines.push('cols_merge_range(col_begin = ' + ExportRgt.name(merge.target) +
            ', col_end = ' + ExportRgt.name(others[0]) + ')');
          break;
        case 'n_pct':
          lines.push('cols_merge_n_pct(col_n = ' + ExportRgt.name(merge.target) +
            ', col_pct = ' + ExportRgt.name(others[0]) + ')');
          break;
        default:
          lines.push('cols_merge(columns = ' + all +
            ', pattern = ' + ExportRgt.str(merge.pattern || '{1} ({2})') + ')');
      }
    }

    /* ---- Formatting ---- */

    for (const rule of spec.format) {
      if (rule.enabled === false) continue;
      const cols = rule.columns.filter((id) => columnsById[id]);
      if (!cols.length) continue;
      const call = ExportRgt.formatCall(rule, cols);
      if (call) lines.push(call);
    }

    if (spec.subs.missing.enabled) {
      lines.push('sub_missing(missing_text = ' + ExportRgt.md(spec.subs.missing.text) + ')');
    }
    if (spec.subs.zero.enabled) {
      lines.push('sub_zero(zero_text = ' + ExportRgt.md(spec.subs.zero.text) + ')');
    }

    /* ---- Summaries ---- */

    for (const summary of spec.summaries.groups) {
      const call = ExportRgt.summaryCall(summary, 'summary_rows', columnsById);
      if (call) lines.push(call);
    }
    for (const summary of spec.summaries.grand) {
      const call = ExportRgt.summaryCall(summary, 'grand_summary_rows', columnsById);
      if (call) lines.push(call);
    }

    /* ---- data_color ---- */

    for (const rule of spec.dataColor) {
      if (rule.enabled === false) continue;
      const cols = rule.columns.filter((id) => columnsById[id]);
      if (!cols.length) continue;

      const args = ['columns = ' + ExportRgt.columnVector(cols)];
      args.push('palette = ' + ExportRgt.strVector(Palettes.byName(rule.palette || 'Blues')));
      if (rule.method && rule.method !== 'numeric') args.push('method = "' + rule.method + '"');
      if (rule.method === 'bin' || rule.method === 'quantile') args.push('n_bins = ' + (rule.bins || 5));
      if (rule.domain && rule.domain.length === 2 && rule.domain.every((n) => n !== null && n !== undefined)) {
        args.push('domain = c(' + rule.domain.join(', ') + ')');
      }
      if (rule.reverse) args.push('reverse = TRUE');
      if (rule.applyTo === 'text') args.push('apply_to = "text"');
      if (rule.autocolorText === false) args.push('autocolor_text = FALSE');
      if (rule.alpha !== undefined && rule.alpha < 1) args.push('alpha = ' + rule.alpha);

      lines.push('data_color(' + args.join(', ') + ')');
    }

    /* ---- Footnotes and notes ---- */

    for (const note of spec.parts.footnotes) {
      const location = ExportRgt.location(note.location, columnsById, model);
      lines.push('tab_footnote(footnote = ' + ExportRgt.md(note.text) +
        (location ? ', locations = ' + location : '') + ')');
    }
    for (const note of spec.parts.sourceNotes) {
      lines.push('tab_source_note(source_note = ' + ExportRgt.md(note.text) + ')');
    }

    /* ---- Style rules ---- */

    for (const rule of spec.styleRules) {
      if (rule.enabled === false || StyleRules.isEmptyStyle(rule.style)) continue;
      const call = ExportRgt.styleCall(rule, columnsById, model);
      if (call) lines.push(call);
    }

    /* ---- Options ---- */

    const changed = OptionsSchema.diff(spec.options);
    const optionArgs = Object.keys(changed).map((key) =>
      ExportRgt.optionName(key) + ' = ' + ExportRgt.optionValue(key, changed[key]));

    if (optionArgs.length) {
      lines.push('tab_options(\n    ' + optionArgs.join(',\n    ') + '\n  )');
    }

    return lines;
  },

  /* ================================================================
     Call builders
     ================================================================ */

  formatCall(rule, cols) {
    const opts = Formatters.resolveOpts(rule.type, rule.opts);
    const args = ['columns = ' + ExportRgt.columnVector(cols)];

    const push = (name, value) => args.push(name + ' = ' + value);

    switch (rule.type) {
      case 'number':
        if (opts.nSigfig) push('n_sigfig', opts.nSigfig);
        else push('decimals', opts.decimals);
        if (!opts.useSeparator) push('use_seps', 'FALSE');
        if (opts.sepMark !== ',') push('sep_mark', ExportRgt.str(opts.sepMark));
        if (opts.decMark !== '.') push('dec_mark', ExportRgt.str(opts.decMark));
        if (opts.dropTrailingZeros) push('drop_trailing_zeros', 'TRUE');
        if (opts.forceSign) push('force_sign', 'TRUE');
        if (opts.scaleBy !== 1) push('scale_by', opts.scaleBy);
        if (opts.suffixing) push('suffixing', 'TRUE');
        if (opts.pattern !== '{x}') push('pattern', ExportRgt.str(opts.pattern));
        return 'fmt_number(' + args.join(', ') + ')';

      case 'integer':
        if (!opts.useSeparator) push('use_seps', 'FALSE');
        if (opts.forceSign) push('force_sign', 'TRUE');
        if (opts.scaleBy !== 1) push('scale_by', opts.scaleBy);
        if (opts.suffixing) push('suffixing', 'TRUE');
        return 'fmt_integer(' + args.join(', ') + ')';

      case 'percent':
        push('decimals', opts.decimals);
        if (opts.alreadyPercent) push('scale_values', 'FALSE');
        if (opts.placement === 'left') push('placement', '"left"');
        if (opts.incl_space) push('incl_space', 'TRUE');
        if (opts.forceSign) push('force_sign', 'TRUE');
        return 'fmt_percent(' + args.join(', ') + ')';

      case 'currency':
        push('currency', ExportRgt.str(opts.symbol || opts.currency));
        push('decimals', opts.decimals);
        if (opts.placement === 'right') push('placement', '"right"');
        if (opts.incl_space) push('incl_space', 'TRUE');
        if (!opts.useSeparator) push('use_seps', 'FALSE');
        return 'fmt_currency(' + args.join(', ') + ')';

      case 'scientific':
        push('decimals', opts.decimals);
        if (opts.expStyle !== 'x10n') push('exp_style', ExportRgt.str(opts.expStyle));
        return 'fmt_scientific(' + args.join(', ') + ')';

      case 'engineering':
        push('decimals', opts.decimals);
        return 'fmt_engineering(' + args.join(', ') + ')';

      case 'date':
        push('date_style', ExportRgt.str(opts.style));
        return 'fmt_date(' + args.join(', ') + ')';

      case 'time':
        push('time_style', ExportRgt.str(opts.style));
        return 'fmt_time(' + args.join(', ') + ')';

      case 'datetime':
        push('date_style', ExportRgt.str(opts.dateStyle));
        push('time_style', ExportRgt.str(opts.timeStyle));
        return 'fmt_datetime(' + args.join(', ') + ')';

      case 'markdown':
        return 'fmt_markdown(' + args.join(', ') + ')';

      case 'passthrough':
        if (opts.pattern !== '{x}') push('pattern', ExportRgt.str(opts.pattern));
        return 'fmt_passthrough(' + args.join(', ') + ')';

      default:
        // `text` has no direct gt equivalent; note it rather than emit something wrong.
        return '# text formatting on ' + cols.join(', ') + ' has no direct gt equivalent';
    }
  },

  summaryCall(summary, fnName, columnsById) {
    const cols = (summary.columns || []).filter((id) => columnsById[id]);
    if (!cols.length || !summary.fns || !summary.fns.length) return null;

    const fns = summary.fns.map((id) => {
      const label = (summary.labels && summary.labels[id]) ||
        (Compute.SUMMARY_FNS.find((f) => f.id === id) || {}).label || id;
      const expr = ExportRgt.summaryExpr(id);
      return ExportRgt.str(label) + ' ~ ' + expr;
    });

    const opts = Formatters.resolveOpts(summary.format || 'number', summary.formatOpts);

    return fnName + '(\n' +
      '    columns = ' + ExportRgt.columnVector(cols) + ',\n' +
      '    fns = list(\n      ' + fns.join(',\n      ') + '\n    ),\n' +
      '    fmt = list(~ fmt_number(., decimals = ' + (opts.decimals === undefined ? 2 : opts.decimals) + '))\n' +
      '  )';
  },

  summaryExpr(id) {
    switch (id) {
      case 'sum': return 'sum(., na.rm = TRUE)';
      case 'mean': return 'mean(., na.rm = TRUE)';
      case 'median': return 'median(., na.rm = TRUE)';
      case 'min': return 'min(., na.rm = TRUE)';
      case 'max': return 'max(., na.rm = TRUE)';
      case 'sd': return 'sd(., na.rm = TRUE)';
      case 'n': return 'sum(!is.na(.))';
      case 'first': return 'dplyr::first(.)';
      case 'last': return 'dplyr::last(.)';
      default: return 'sum(., na.rm = TRUE)';
    }
  },

  styleCall(rule, columnsById, model) {
    const styles = [];
    const text = rule.style.text || {};
    const textArgs = [];

    if (text.color) textArgs.push('color = ' + ExportRgt.str(text.color));
    if (text.size) textArgs.push('size = ' + ExportRgt.size(text.size));
    if (text.weight) textArgs.push('weight = ' + ExportRgt.str(text.weight));
    if (text.style) textArgs.push('style = ' + ExportRgt.str(text.style));
    if (text.align) textArgs.push('align = ' + ExportRgt.str(text.align));
    if (text.vAlign) textArgs.push('v_align = ' + ExportRgt.str(text.vAlign));
    if (text.transform) textArgs.push('transform = ' + ExportRgt.str(text.transform));
    if (text.decorate && text.decorate !== 'none') {
      textArgs.push('decorate = ' + ExportRgt.str(text.decorate === 'line-through' ? 'strikethrough' : text.decorate));
    }
    if (text.stretch) textArgs.push('stretch = ' + ExportRgt.str(text.stretch));
    if (text.whitespace) textArgs.push('whitespace = ' + ExportRgt.str(text.whitespace));
    if (text.indent) textArgs.push('indent = ' + ExportRgt.size(text.indent));
    if (text.font) textArgs.push('font = ' + ExportRgt.fontRef(text.font));

    if (textArgs.length) styles.push('cell_text(' + textArgs.join(', ') + ')');

    if (rule.style.fill && rule.style.fill.color) {
      const fillArgs = ['color = ' + ExportRgt.str(rule.style.fill.color)];
      if (rule.style.fill.alpha !== undefined && rule.style.fill.alpha < 1) {
        fillArgs.push('alpha = ' + rule.style.fill.alpha);
      }
      styles.push('cell_fill(' + fillArgs.join(', ') + ')');
    }

    // gt groups borders by side, so sides sharing a look collapse into one call.
    const borders = rule.style.borders || {};
    const bySignature = new Map();
    for (const side of StyleRules.SIDES) {
      const border = borders[side];
      if (!border || !border.style || border.style === 'none') continue;
      const signature = border.style + '|' + border.width + '|' + border.color;
      if (!bySignature.has(signature)) bySignature.set(signature, { border: border, sides: [] });
      bySignature.get(signature).sides.push(side);
    }
    for (const entry of bySignature.values()) {
      styles.push('cell_borders(sides = ' + ExportRgt.strVector(entry.sides) +
        ', color = ' + ExportRgt.str(entry.border.color) +
        ', style = ' + ExportRgt.str(entry.border.style) +
        ', weight = ' + ExportRgt.size(entry.border.width) + ')');
    }

    if (!styles.length) return null;

    const locations = rule.locations
      .map((loc) => ExportRgt.locationCall(loc, columnsById, model))
      .filter(Boolean);
    if (!locations.length) return null;

    return 'tab_style(\n' +
      '    style = list(' + styles.join(', ') + '),\n' +
      '    locations = ' + (locations.length === 1 ? locations[0] : 'list(' + locations.join(', ') + ')') + '\n' +
      '  )';
  },

  /** A style rule location as a `cells_*()` call. */
  locationCall(loc, columnsById, model) {
    const args = [];
    const cols = (loc.columns || []).filter((id) => columnsById[id]);

    const rowsArg = () => {
      if (!loc.rows) return null;
      if (loc.rows.mode === 'index' && loc.rows.indices.length) {
        // gt rows are 1-based.
        return 'rows = c(' + loc.rows.indices.map((i) => i + 1).join(', ') + ')';
      }
      if (loc.rows.mode === 'expr' && loc.rows.expr) {
        return 'rows = ' + ExportRgt.translateExpr(loc.rows.expr);
      }
      return null;
    };

    switch (loc.part) {
      case 'body':
        if (cols.length) args.push('columns = ' + ExportRgt.columnVector(cols));
        if (rowsArg()) args.push(rowsArg());
        return 'cells_body(' + args.join(', ') + ')';

      case 'stub':
        if (rowsArg()) args.push(rowsArg());
        return 'cells_stub(' + args.join(', ') + ')';

      case 'column_labels':
        if (cols.length) args.push('columns = ' + ExportRgt.columnVector(cols));
        return 'cells_column_labels(' + args.join(', ') + ')';

      case 'column_spanners': {
        const spanners = (loc.spanners || [])
          .map((id) => (Store.get().structure.spanners.find((sp) => sp.id === id) || {}).label)
          .filter(Boolean);
        return 'cells_column_spanners(spanners = ' +
          (spanners.length ? ExportRgt.strVector(spanners) : 'everything()') + ')';
      }

      case 'stubhead':
        return 'cells_stubhead()';

      case 'row_groups':
        return 'cells_row_groups(' +
          ((loc.groups || []).length ? 'groups = ' + ExportRgt.strVector(loc.groups) : '') + ')';

      case 'summary':
        if (cols.length) args.push('columns = ' + ExportRgt.columnVector(cols));
        return 'cells_summary(' + args.join(', ') + ')';

      case 'grand_summary':
        if (cols.length) args.push('columns = ' + ExportRgt.columnVector(cols));
        return 'cells_grand_summary(' + args.join(', ') + ')';

      case 'title':
        return 'cells_title(groups = "title")';

      case 'subtitle':
        return 'cells_title(groups = "subtitle")';

      case 'footnotes':
        return 'cells_footnotes()';

      case 'source_notes':
        return 'cells_source_notes()';

      default:
        return null;
    }
  },

  /** A footnote location, which uses the same helpers. */
  location(loc, columnsById, model) {
    if (!loc || !loc.part) return null;
    return ExportRgt.locationCall({
      part: loc.part,
      columns: loc.colId ? [loc.colId] : [],
      rows: loc.srcIndex !== undefined ? { mode: 'index', indices: [loc.srcIndex] } : null,
      groups: loc.groupId ? [loc.groupId] : [],
      spanners: loc.spannerId ? [loc.spannerId] : []
    }, columnsById, model);
  },

  /**
   * Translate a row expression from JavaScript to R.
   *
   * Only the common operators are handled — enough for the conditions people
   * actually write. Anything unrecognised is passed through with a comment so
   * the R is at least reviewable rather than silently wrong.
   */
  translateExpr(expr) {
    const translated = String(expr)
      .replace(/&&/g, '&')
      .replace(/\|\|/g, '|')
      .replace(/===/g, '==')
      .replace(/!==/g, '!=')
      .replace(/\bnull\b/g, 'NA')
      .replace(/\btrue\b/g, 'TRUE')
      .replace(/\bfalse\b/g, 'FALSE')
      .replace(/Math\.abs\(/g, 'abs(')
      .replace(/Math\.max\(/g, 'max(')
      .replace(/Math\.min\(/g, 'min(')
      .replace(/"/g, '"');

    return translated;
  },

  /* ================================================================
     Literals
     ================================================================ */

  /** An R symbol, backtick-quoted when the id is not syntactic. */
  symbol(id) {
    return /^[A-Za-z.][A-Za-z0-9._]*$/.test(id) && !/^\.\d/.test(id)
      ? id
      : '`' + id + '`';
  },

  /** A column reference as a quoted name, for `rowname_col` and friends. */
  name(id) {
    return '"' + String(id).replace(/"/g, '\\"') + '"';
  },

  /** `c(a, b, c)` of bare column symbols. */
  columnVector(ids) {
    if (ids.length === 1) return ExportRgt.symbol(ids[0]);
    return 'c(' + ids.map(ExportRgt.symbol).join(', ') + ')';
  },

  str(value) {
    return '"' + String(value === null || value === undefined ? '' : value)
      .replace(/\\/g, '\\\\')
      .replace(/"/g, '\\"')
      .replace(/\n/g, '\\n') + '"';
  },

  strVector(values) {
    if (values.length === 1) return ExportRgt.str(values[0]);
    return 'c(' + values.map(ExportRgt.str).join(', ') + ')';
  },

  /** Text carrying markup becomes `md()`, so gt renders it too. */
  md(text) {
    const str = String(text === null || text === undefined ? '' : text);
    if (!Markup.hasMarkup(str)) return ExportRgt.str(str);

    // This app's markup is close enough to Markdown for bold and italic; the
    // sup/sub forms need HTML, so those go through html().
    if (/\^\{|_\{|\^\S|_\S/.test(str)) {
      return 'html(' + ExportRgt.str(Markup.toHtml(str)) + ')';
    }
    return 'md(' + ExportRgt.str(str) + ')';
  },

  /** A CSS length as gt's `px()` or `pct()` helper. */
  width(value) {
    const str = String(value);
    if (str.indexOf('%') >= 0) return 'pct(' + parseFloat(str) + ')';
    const num = Util.cssNumber(str);
    return num === null ? ExportRgt.str(str) : 'px(' + num + ')';
  },

  size(value) {
    const str = String(value);
    if (str.indexOf('%') >= 0 || str.indexOf('em') >= 0) return ExportRgt.str(str);
    const num = Util.cssNumber(str);
    return num === null ? ExportRgt.str(str) : 'px(' + num + ')';
  },

  /**
   * A font reference as gt sees it.
   *
   * Google families map onto `google_font()`. An uploaded face has no gt
   * equivalent — gt cannot inline a binary — so it is named and left to the R
   * session to have installed, with the fallback stack behind it.
   */
  fontRef(id) {
    const family = Fonts.webFamily(id);
    if (family) return 'google_font(name = ' + ExportRgt.str(family) + ')';

    const local = Fonts.embedded(id);
    if (local) return ExportRgt.str(Fonts.stack(id));

    return ExportRgt.str(Fonts.stack(id));
  },

  /** `table.font.size` becomes `table_font_size`, gt's argument spelling. */
  optionName(key) {
    return key.replace(/\./g, '_');
  },

  optionValue(key, value) {
    const option = OptionsSchema.get(key);
    if (!option) return ExportRgt.str(value);

    if (option.type === 'bool') return value ? 'TRUE' : 'FALSE';
    if (option.type === 'fonts') return ExportRgt.fontRef(value);
    if (option.type === 'len') {
      const str = String(value);
      if (str === 'auto' || str.indexOf('%') >= 0 || str.indexOf('em') >= 0) return ExportRgt.str(str);
      const num = Util.cssNumber(str);
      return num === null ? ExportRgt.str(str) : 'px(' + num + ')';
    }
    if (option.type === 'color' && !value) return 'NA';

    return ExportRgt.str(value);
  },

  /** One data value as an R literal. */
  value(raw, type) {
    if (Util.isMissing(raw)) return 'NA';
    if (type === 'number') {
      const num = Util.toNumber(raw);
      return num === null ? ExportRgt.str(raw) : String(num);
    }
    if (type === 'bool') {
      return /^(true|yes|t)$/i.test(String(raw).trim()) ? 'TRUE' : 'FALSE';
    }
    return ExportRgt.str(raw);
  }
};
