/**
 * export-rgt.js
 *
 * Emits the equivalent gt pipeline in R.
 *
 * The spec was designed to mirror gt's own decomposition, so this is close to a
 * direct transcription: each section becomes the call it was modelled on. That
 * is the point of the format — a table designed in the GUI can go straight into
 * a Quarto or R Markdown document and stay reproducible there.
 */

const ExportRgt = {

  /** Above this, the data is referenced rather than inlined. */
  MAX_INLINE_ROWS: 300,

  /**
   * @param {Object} spec
   * @param {Object} model - the resolved model, for derived values
   * @returns {string} R source
   */
  build(spec, model) {
    const out = [];
    // The file as imported. Every step is emitted as code below, so the block
    // is the data the user actually has — which is also what makes the
    // `readr::read_csv()` branch honest for a pivoted table.
    const shaped = Pipeline.run(spec.source, spec.pipeline, Pipeline.inlineSplit());
    const working = { columns: shaped.columns, rows: shaped.items.map((item) => item.row) };

    out.push('# Generated by Table Builder');
    out.push('# ' + new Date().toISOString().slice(0, 10));
    out.push('');
    out.push('library(gt)');
    out.push('library(dplyr)');
    out.push('');

    out.push.apply(out, ExportRgt.data(spec, working));
    out.push('');

    const pipeline = ExportRgt.pipeline(spec, model, working);
    out.push('tbl <- data |>');
    out.push(pipeline.map((line, i) => '  ' + line + (i < pipeline.length - 1 ? ' |>' : '')).join('\n'));
    out.push('');
    out.push('tbl');
    out.push('');
    out.push('# gtsave(tbl, "table.html")');
    out.push('# gtsave(tbl, "table.png", expand = 10)');
    out.push('');

    return out.join('\n');
  },

  /* ================================================================
     Data
     ================================================================ */

  data(spec, working) {
    const out = [];

    if (working.rows.length > ExportRgt.MAX_INLINE_ROWS) {
      out.push('# ' + working.rows.length + ' rows is too many to inline readably.');
      out.push('# Point this at your own file — the column names below are what the');
      out.push('# rest of the pipeline expects.');
      out.push('# Columns: ' + working.columns.map((c) => c.id).join(', '));
      out.push('data <- readr::read_csv("' + (spec.source.filename || 'data.csv') + '")');
      return out;
    }

    out.push('data <- tibble::tribble(');
    out.push('  ' + working.columns.map((col) => '~' + ExportRgt.symbol(col.id)).join(', ') + ',');

    working.rows.forEach((row, index) => {
      const values = working.columns.map((col) => ExportRgt.value(row[col.id], col.type));
      out.push('  ' + values.join(', ') + (index < working.rows.length - 1 ? ',' : ''));
    });

    out.push(')');
    return out;
  },

  /**
   * `dplyr::mutate()` for the cell corrections, or null if there are none.
   *
   * Emitted as a row-numbered `case_when` rather than baked into the tibble
   * above, for two reasons. A correction stays legible *as* a correction, so
   * the R says what was changed rather than presenting the fixed value as
   * though it came out of the file. And the branch that points at
   * `readr::read_csv()` instead of inlining the rows gets corrected too — bake
   * them into the tibble and every table over `MAX_INLINE_ROWS` would export
   * uncorrected.
   *
   * Row numbers are positions in the data as imported, which is exactly what
   * `srcIndex` counts, and `dplyr::mutate` runs before the `filter()` below, so
   * nothing has been dropped from underneath them yet.
   *
   * Only *applied* corrections are emitted. One whose guard no longer matches
   * did not change the preview and must not change the export.
   */
  correctionCall(applied, columnsById) {
    if (!applied || !applied.length) return null;

    const args = [];
    for (const [colId, entries] of Util.groupBy(applied, (c) => c.colId)) {
      const column = columnsById[colId];
      if (!column) continue;
      const symbol = ExportRgt.symbol(colId);
      // `rRow` is where the correction landed at this point in the pipeline,
      // which is what `row_number()` will be here — not the row's original
      // index, which a filter earlier in the pipeline will have moved.
      const clauses = entries.map((c) =>
        'dplyr::row_number() == ' + (c.rRow || (c.srcIndex + 1)) + ' ~ ' +
        ExportRgt.value(c.to, column.type));
      args.push(symbol + ' = dplyr::case_when(' + clauses.join(', ') +
        ', .default = ' + symbol + ')');
    }

    return args.length ? 'dplyr::mutate(' + args.join(', ') + ')' : null;
  },

  /** `dplyr::filter()` for a filter step, or null when nothing is applicable. */
  filterCall(step, columnsById) {
    const conditions = Filter.active(step, columnsById);
    if (!conditions.length) return null;

    const joiner = (step.match === 'any') ? ' | ' : ', ';
    const parts = conditions.map((condition) => {
      const op = Filter.get(condition.op);
      const column = columnsById[condition.col];
      const numeric = !!(column && column.type === 'number');
      const expr = op.r(ExportRgt.symbol(condition.col), condition.value, condition.value2, numeric);
      // `any` joins with `|`, so anything that is itself a compound (between,
      // is empty) has to be parenthesised or the precedence changes.
      return (joiner === ' | ' && /[|&]/.test(expr)) ? '(' + expr + ')' : expr;
    });
    return 'dplyr::filter(' + parts.join(joiner) + ')';
  },

  /* ================================================================
     Pipeline
     ================================================================ */

  pipeline(spec, model, working) {
    const st = spec.structure;
    const lines = [];
    // The pipeline's *output* — everything below `gt()` names the columns the
    // table ends up with, while each data step above names its own.
    const columnsById = model.columnsById || {};

    /* ---- The data stage, in the order the pipeline puts it ---- */

    // Each step emits its own R — see the `r()` on every entry in
    // `Pipeline.TYPES`, which sits beside the transform the preview applies so
    // the two cannot drift. Steps up to and including the last pivot are
    // already in the `data` block above, because a pivot's column ids cannot
    // yet be reproduced in R; everything after it is emitted here.
    // **The columns as of each step's own position**, not the pipeline's
    // output — a pivot's `names_from` must name the long file's columns, and a
    // sort below a pivot must name the wide ones. Same reasoning as the Steps
    // panel's `columnsAt`.
    (spec.pipeline || []).forEach((step, index) => {
      const def = Pipeline.type(step.type);
      if (!def || def.stage !== 'data' || !def.r || !Spec.isEnabled(step)) return;

      const at = Pipeline.run(spec.source, spec.pipeline, index);
      const byId = {};
      for (const col of at.columns) byId[col.id] = col;

      const call = def.r(step, { byId: byId, applied: model.corrections || [] });
      if (call) lines.push(call);
    });

    /* ---- gt() ---- */

    // From the resolved model, not the spec: a `stub` step naming a column an
    // earlier step removed is inert, and the export has to agree with the
    // preview about that rather than name a column gt would not find.
    const gtArgs = [];
    if (model.stubCol) gtArgs.push('rowname_col = ' + ExportRgt.name(model.stubCol));
    if (model.groupCol) gtArgs.push('groupname_col = ' + ExportRgt.name(model.groupCol));
    lines.push('gt(' + gtArgs.join(', ') + ')');

    // A hand-ordered group sequence was preview-only until now: nothing
    // emitted it, so the exported table silently reverted to first-seen order.
    if (model.groupCol && (model.groupOrder || []).length) {
      lines.push('row_group_order(groups = ' + ExportRgt.strVector(model.groupOrder) + ')');
    }

    /* ---- Header ---- */

    if (spec.parts.title || spec.parts.subtitle) {
      const args = [];
      if (spec.parts.title) args.push('title = ' + ExportRgt.md(spec.parts.title));
      if (spec.parts.subtitle) args.push('subtitle = ' + ExportRgt.md(spec.parts.subtitle));
      lines.push('tab_header(' + args.join(', ') + ')');
    }

    if (spec.parts.stubhead) {
      lines.push('tab_stubhead(label = ' + ExportRgt.md(spec.parts.stubhead) + ')');
    }
    if (spec.parts.caption) {
      lines.push('tab_caption(caption = ' + ExportRgt.md(spec.parts.caption) + ')');
    }

    /* ---- Columns ---- */

    // The stub and group columns are consumed by gt() itself and are no longer
    // addressable as ordinary columns, so they stay out of every cols_* call.
    const consumed = new Set([model.stubCol, model.groupCol].filter(Boolean));

    const hidden = st.hidden.filter((id) => columnsById[id] && !consumed.has(id));
    if (hidden.length) {
      lines.push('cols_hide(columns = ' + ExportRgt.columnVector(hidden) + ')');
    }

    // Ordered by the preference, not filtered by it: `columnOrder` never holds
    // a pivot's output ids, so filtering by it emitted a `cols_move_to_start()`
    // naming two of eleven columns — and `cols_label`, `cols_align` and
    // `cols_width` below are all derived from this list, so every
    // pivot-derived column lost its label in the exported table.
    const visible = Spec.orderColumns(st.columnOrder, Object.keys(columnsById))
      .filter((id) => !consumed.has(id) && hidden.indexOf(id) < 0);
    if (visible.length > 1) {
      lines.push('cols_move_to_start(columns = ' + ExportRgt.columnVector(visible) + ')');
    }

    // The emitted tibble is named by column *id*, so that is what gt will use
    // as a label unless told otherwise. Anything the GUI shows differently has
    // to be emitted — including the humanised defaults, or the R table would
    // read `mean_age` where the preview reads "Mean age".
    // Through `Spec.columnLabel`, not `st.labels` directly. A pivot's output
    // has no entry there — its label comes from the column's own `shortName` —
    // so reading the map gave every pivot-derived column its raw id in the
    // exported table where the preview reads "Employment". `columnLabel` is the
    // one place that decides what the table says a column is called.
    const labels = [];
    for (const id of visible) {
      const label = Spec.columnLabel(spec, columnsById[id]);
      if (label === undefined || label === id) continue;
      labels.push(ExportRgt.symbol(id) + ' = ' + ExportRgt.md(label));
    }
    if (labels.length) lines.push('cols_label(' + labels.join(', ') + ')');

    const alignGroups = Util.groupBy(
      visible.filter((id) => st.align[id] && st.align[id] !== 'auto'),
      (id) => st.align[id]
    );
    for (const [align, ids] of alignGroups) {
      lines.push('cols_align(align = "' + align + '", columns = ' + ExportRgt.columnVector(ids) + ')');
    }

    const widths = Object.keys(st.widths)
      .filter((id) => columnsById[id] && st.widths[id] && !consumed.has(id));
    if (widths.length) {
      lines.push('cols_width(' + widths.map((id) =>
        ExportRgt.symbol(id) + ' ~ ' + ExportRgt.width(st.widths[id])).join(', ') + ')');
    }

    /* ---- Spanners ---- */

    // Innermost first, so gt stacks them the way the preview shows them.
    // Already in pipeline order, and already resolved against the columns
    // that survived — `Pipeline.run` drops a group whose columns have gone.
    const spanners = (model.spanners || []).slice().sort((a, b) => (a.level || 1) - (b.level || 1));
    const spannerIds = ExportRgt.spannerIds(model.spanners || []);
    const claimed = {};   // level -> Set(colId), for the overlap case below
    for (const spanner of spanners) {
      // **In display order**, not the order the step stored them in.
      // `tab_spanner()` gathers its columns together and preserves the order it
      // was given, so `columns = c(n, metric)` reorders the table to put `n`
      // first — where the preview draws the spanner over whatever order those
      // columns are already in. Sorting by the visible order makes the gather a
      // no-op for columns that are already adjacent.
      const cols = visible.filter((id) => spanner.columns.indexOf(id) >= 0);
      if (!cols.length) continue;
      // **`id` is not optional here.** gt defaults it to the label and requires
      // it to be unique, and a nested pivot repeats its inner labels by
      // construction: `nameCols = [year, quarter]` over two value columns gives
      // Q1 and Q2 under each year, so the R came out with two
      // `tab_spanner(label = "Q1", …)` calls and gt rejected the second. The
      // most ordinary use of the app's own pivot exported R that would not run.
      const args = ['label = ' + ExportRgt.md(spanner.label),
        'id = ' + ExportRgt.str(spannerIds[spanner.id]),
        'columns = ' + ExportRgt.columnVector(cols)];

      // gt refuses to overwrite a spanner on a column it already covers at
      // that level, so overlapping groups made the whole script stop. The
      // preview resolves the same clash by letting the later one win, which is
      // what `replace` asks for — so the R runs and matches. `compute.js` warns
      // about the arrangement either way; this only keeps the export from
      // being the place it is discovered.
      const level = spanner.level || 1;
      const overlapped = cols.some((colId) => claimed[level] && claimed[level].has(colId));
      if (overlapped) args.push('replace = TRUE');
      if (!claimed[level]) claimed[level] = new Set();
      for (const colId of cols) claimed[level].add(colId);

      lines.push('tab_spanner(' + args.join(', ') + ')');
    }

    /* ---- Indented row labels ---- */

    // Preview-only until now: `structure.stubIndent` was read by `compute.js`,
    // `render-html.js` and `export-latex.js` and emitted by nothing, so an
    // indented stub came out flat in gt.
    //
    // Grouped by level, because `tab_stub_indent()` takes one indent and a set
    // of rows — and by **displayed position**, not source index: gt counts rows
    // in the data frame it was handed, which `dplyr::arrange()` has already put
    // in display order, so a filter or a sort above moves every later number.
    const indents = new Map();
    (model.rowSequence || []).forEach((item, position) => {
      const level = Util.clamp(
        Math.round((st.stubIndent || {})[item.srcIndex] || 0), 0, 5);
      if (!level) return;
      if (!indents.has(level)) indents.set(level, []);
      indents.get(level).push(position + 1);
    });
    for (const level of Array.from(indents.keys()).sort((a, b) => a - b)) {
      lines.push('tab_stub_indent(rows = c(' + indents.get(level).join(', ') +
        '), indent = ' + level + ')');
    }

    /* ---- Merges ---- */

    for (const merge of (model.merges || [])) {
      if (!columnsById[merge.target]) continue;
      const others = merge.columns.filter((id) => columnsById[id]);
      if (!others.length) continue;
      const all = ExportRgt.columnVector([merge.target].concat(others));

      switch (merge.type) {
        case 'uncert':
          lines.push('cols_merge_uncert(col_val = ' + ExportRgt.name(merge.target) +
            ', col_uncert = ' + ExportRgt.name(others[0]) + ')');
          break;
        case 'range':
          lines.push('cols_merge_range(col_begin = ' + ExportRgt.name(merge.target) +
            ', col_end = ' + ExportRgt.name(others[0]) + ')');
          break;
        case 'n_pct':
          lines.push('cols_merge_n_pct(col_n = ' + ExportRgt.name(merge.target) +
            ', col_pct = ' + ExportRgt.name(others[0]) + ')');
          break;
        default:
          lines.push('cols_merge(columns = ' + all +
            ', pattern = ' + ExportRgt.str(merge.pattern || '{1} ({2})') + ')');
      }
    }

    /* ---- Formatting ---- */

    for (const rule of spec.format) {
      if (!Spec.isEnabled(rule)) continue;
      const cols = rule.columns.filter((id) => columnsById[id]);
      if (!cols.length) continue;
      const call = ExportRgt.formatCall(rule, cols);
      if (call) lines.push(call);
    }

    if (spec.subs.missing.enabled) {
      lines.push('sub_missing(missing_text = ' + ExportRgt.md(spec.subs.missing.text) + ')');
    }
    if (spec.subs.zero.enabled) {
      lines.push('sub_zero(zero_text = ' + ExportRgt.md(spec.subs.zero.text) + ')');
    }

    /* ---- Summaries ---- */

    // Emitted from the pipeline, in the order the steps sit in — see the
    // `summary` type's own `r()`. gt takes group summaries before grand ones
    // either way, so the order among them is the user's to choose.
    for (const step of (spec.pipeline || [])) {
      if (step.type !== 'summary' || !Spec.isEnabled(step)) continue;
      const def = Pipeline.type('summary');
      const call = def.r(step, { byId: columnsById, formatPlan: model.formatPlan });
      if (call) lines.push(call);
    }

    /* ---- data_color ---- */

    // `gt` fits a domain per column by default (`direction = "column"`), so a
    // scale the preview shared across several columns arrives in R as several
    // different scales unless the range is written down — and a rule fitted
    // per column arrives shared unless it is split into a call per column.
    // Both were silent: the two settings emitted byte-identical R.
    //
    // The domain comes from `model.colorScales`, where `buildColorPlan` fitted
    // it, rather than being computed again here. It already carries the
    // explicit domain and the midpoint's symmetric widening, so re-deriving it
    // would be a second producer of a number the pure step has decided.
    for (const rule of spec.dataColor) {
      if (!Spec.isEnabled(rule)) continue;
      const cols = rule.columns.filter((id) => columnsById[id]);
      if (!cols.length) continue;

      const plan = (model.colorScales || []).find((entry) => entry.id === rule.id);
      const method = Spec.colorMethod(rule);
      const shared = rule.sharedDomain !== false;

      // A factor's breaks follow its level set, so it cannot be pinned with a
      // domain and sharing one across columns is not expressible in gt at all
      // — say so rather than emitting R that quietly means the other thing.
      if (shared && cols.length > 1 && method === 'factor') {
        lines.push('# the preview fits one ' + method + ' scale across ' +
          cols.join(', ') + '; gt fits one per column and has no argument for it');
      }

      // Which columns supply the values, and which get painted. gt takes the
      // values from `columns` and paints `target_columns`, so a rule that
      // colours one column by another's numbers swaps the two round here.
      const valueCols = Spec.colorValueColumns(rule).filter((id) => columnsById[id]);
      if (!valueCols.length) continue;
      const targeted = valueCols.join() !== cols.join();

      const groups = shared || targeted ? [cols] : cols.map((id) => [id]);

      for (const group of groups) {
        const source = targeted ? valueCols : group;
        const args = ['columns = ' + ExportRgt.columnVector(source)];
        if (targeted) args.push('target_columns = ' + ExportRgt.columnVector(group));

        /*
         * The levels and the palette go out together and in step. gt maps
         * `palette[i]` onto `levels[i]` positionally — verified against real
         * gt rather than assumed — so a categorical rule with colours picked
         * per level is exactly expressible, provided both lists come from the
         * one place that decided them. `compute.js` recorded the order it
         * mapped; re-deriving it here would be a second producer of which
         * category is which colour.
         */
        if (method === 'factor' && plan && plan.levels && plan.levels.length && plan.levelColors) {
          args.push('levels = ' + ExportRgt.strVector(plan.levels));
          args.push('palette = ' + ExportRgt.strVector(plan.levels.map((l) => plan.levelColors[l])));
        } else {
          args.push('palette = ' + ExportRgt.strVector(Spec.colorRamp(rule)));
        }
        if (method !== 'numeric') args.push('method = "' + method + '"');

        const domain = plan && plan.domains ? plan.domains[group[0]] : null;
        if (domain && method === 'numeric') {
          args.push('domain = c(' + domain.map(ExportRgt.rNumber).join(', ') + ')');
        }

        if (rule.naColor) args.push('na_color = "' + rule.naColor + '"');
        if (rule.reverse) args.push('reverse = TRUE');
        if (rule.applyTo === 'text') args.push('apply_to = "text"');
        if (rule.autocolorText === false) {
          args.push('autocolor_text = FALSE');
        } else if (rule.applyTo !== 'text') {
          // The two colours it flips between are the table's, not gt's own
          // #FFFFFF/#000000 — `table.font.color` defaults to #333333 here, so
          // the flipped text differed from the preview on a default table.
          // The algorithm is the rule's own now, and `Palettes.readableOn`
          // implements both: APCA and WCAG disagree about a third of ordinary
          // fills, so emitting one while the preview computed the other paints
          // different text in the two artefacts.
          const contrast = Spec.colorContrast(rule, spec.options);
          args.push('autocolor_light = "' + contrast.light + '"');
          args.push('autocolor_dark = "' + contrast.dark + '"');
          args.push('contrast_algo = "' + contrast.algo + '"');
        }
        if (rule.alpha !== undefined && rule.alpha < 1) args.push('alpha = ' + rule.alpha);

        lines.push('data_color(' + args.join(', ') + ')');
      }
    }

    /* ---- Footnotes and notes ---- */

    for (const note of spec.parts.footnotes) {
      const location = ExportRgt.location(note.location, columnsById, model);
      lines.push('tab_footnote(footnote = ' + ExportRgt.md(note.text) +
        (location ? ', locations = ' + location : '') + ')');
    }
    for (const note of spec.parts.sourceNotes) {
      lines.push('tab_source_note(source_note = ' + ExportRgt.md(note.text) + ')');
    }

    /* ---- Style rules ---- */

    for (const rule of spec.styleRules) {
      if (!Spec.isEnabled(rule) || StyleRules.isEmptyStyle(rule.style)) continue;
      const call = ExportRgt.styleCall(rule, columnsById, model);
      if (call) lines.push(call);
    }

    /* ---- Options gt has no argument for ---- */

    // Before `tab_options()` only so the generated script reads in the order it
    // is built; gt does not care. These are the five schema keys `tab_options()`
    // has no counterpart for — it carries nothing about spanners at all — so
    // they reach gt the way gt expresses them, as a style on the part they
    // govern. Dropping them would lose a look the preview shows, which is the
    // objection that keeps `parts.captionAlign` out of `spec.options`
    // altogether.
    lines.push.apply(lines, ExportRgt.optionStyleCalls(spec.options));

    /* ---- Options ---- */

    // Resolved, not raw. gt applies `row_group.*` to the group heading row only,
    // so a row group shown as a column needs the value written into gt's own
    // `stub_row_group.*` argument or the exported table loses a look the preview
    // shows. The renderer resolves through the same function, which is what keeps
    // the two from disagreeing.
    const changed = OptionsSchema.diff(
      OptionsSchema.withGroupColumnOverrides(spec.options));

    // Only the ones gt has an argument for. `tab_options()` takes no `...`, so
    // a single name it does not know makes the whole call — and therefore the
    // whole script — fail. The five it does not have are emitted as
    // `tab_style()` above instead; see `ExportRgt.optionStyleCalls`.
    const optionArgs = Object.keys(changed)
      .filter((key) => !OptionsSchema.NOT_IN_TAB_OPTIONS[key])
      .map((key) => ExportRgt.optionName(key) + ' = ' + ExportRgt.optionValue(key, changed[key]));

    if (optionArgs.length) {
      lines.push('tab_options(\n    ' + optionArgs.join(',\n    ') + '\n  )');
    }

    return lines;
  },

  /* ================================================================
     Call builders
     ================================================================ */

  formatCall(rule, cols) {
    const opts = Formatters.resolveOpts(rule.type, rule.opts);
    const args = ['columns = ' + ExportRgt.columnVector(cols)];

    const push = (name, value) => args.push(name + ' = ' + value);

    switch (rule.type) {
      case 'number':
        if (opts.nSigfig) push('n_sigfig', opts.nSigfig);
        else push('decimals', opts.decimals);
        if (!opts.useSeparator) push('use_seps', 'FALSE');
        if (opts.sepMark !== ',') push('sep_mark', ExportRgt.str(opts.sepMark));
        if (opts.decMark !== '.') push('dec_mark', ExportRgt.str(opts.decMark));
        if (opts.dropTrailingZeros) push('drop_trailing_zeros', 'TRUE');
        if (opts.forceSign) push('force_sign', 'TRUE');
        if (opts.scaleBy !== 1) push('scale_by', opts.scaleBy);
        if (opts.suffixing) push('suffixing', 'TRUE');
        if (opts.pattern !== '{x}') push('pattern', ExportRgt.str(opts.pattern));
        return 'fmt_number(' + args.join(', ') + ')';

      case 'integer':
        if (!opts.useSeparator) push('use_seps', 'FALSE');
        if (opts.forceSign) push('force_sign', 'TRUE');
        if (opts.scaleBy !== 1) push('scale_by', opts.scaleBy);
        if (opts.suffixing) push('suffixing', 'TRUE');
        return 'fmt_integer(' + args.join(', ') + ')';

      case 'percent':
        push('decimals', opts.decimals);
        if (opts.alreadyPercent) push('scale_values', 'FALSE');
        if (opts.placement === 'left') push('placement', '"left"');
        if (opts.incl_space) push('incl_space', 'TRUE');
        if (opts.forceSign) push('force_sign', 'TRUE');
        return 'fmt_percent(' + args.join(', ') + ')';

      case 'currency':
        push('currency', ExportRgt.str(opts.symbol || opts.currency));
        push('decimals', opts.decimals);
        if (opts.placement === 'right') push('placement', '"right"');
        if (opts.incl_space) push('incl_space', 'TRUE');
        if (!opts.useSeparator) push('use_seps', 'FALSE');
        return 'fmt_currency(' + args.join(', ') + ')';

      case 'scientific':
        push('decimals', opts.decimals);
        if (opts.expStyle !== 'x10n') push('exp_style', ExportRgt.str(opts.expStyle));
        return 'fmt_scientific(' + args.join(', ') + ')';

      case 'engineering':
        push('decimals', opts.decimals);
        return 'fmt_engineering(' + args.join(', ') + ')';

      case 'date':
        push('date_style', ExportRgt.str(opts.style));
        return 'fmt_date(' + args.join(', ') + ')';

      case 'time':
        push('time_style', ExportRgt.str(opts.style));
        return 'fmt_time(' + args.join(', ') + ')';

      case 'datetime':
        push('date_style', ExportRgt.str(opts.dateStyle));
        push('time_style', ExportRgt.str(opts.timeStyle));
        return 'fmt_datetime(' + args.join(', ') + ')';

      case 'markdown':
        return 'fmt_markdown(' + args.join(', ') + ')';

      case 'passthrough':
        if (opts.pattern !== '{x}') push('pattern', ExportRgt.str(opts.pattern));
        return 'fmt_passthrough(' + args.join(', ') + ')';

      default:
        // `text` has no direct gt equivalent; note it rather than emit something wrong.
        return '# text formatting on ' + cols.join(', ') + ' has no direct gt equivalent';
    }
  },

  summaryCall(summary, fnName, columnsById, formatPlan) {
    const cols = (summary.columns || []).filter((id) => columnsById[id]);
    if (!cols.length || !summary.fns || !summary.fns.length) return null;
    // An unset format follows the first column being totalled, as the preview
    // does — `Compute.summaryRows` decides it and `model.formatPlan` carries
    // the answer, so the two cannot pick differently.
    const inherited = (formatPlan || {})[cols[0]];

    const fns = summary.fns.map((id) => {
      const label = (summary.labels && summary.labels[id]) ||
        (Compute.SUMMARY_FNS.find((f) => f.id === id) || {}).label || id;
      const expr = ExportRgt.summaryExpr(id);
      return ExportRgt.str(label) + ' ~ ' + expr;
    });

    // An unset format follows the column, exactly as the preview does — see the
    // note in `Compute.summaryRows`. `fmtRef` is resolved by the caller, which
    // is the only place that knows the format plan.
    const type = summary.format || (inherited ? inherited.type : 'number');
    const opts = Formatters.resolveOpts(type,
      summary.formatOpts || (inherited ? inherited.opts : null));

    return fnName + '(\n' +
      '    columns = ' + ExportRgt.columnVector(cols) + ',\n' +
      '    fns = list(\n      ' + fns.join(',\n      ') + '\n    ),\n' +
      '    fmt = list(~ fmt_number(., decimals = ' + (opts.decimals === undefined ? 2 : opts.decimals) + '))\n' +
      '  )';
  },

  summaryExpr(id) {
    switch (id) {
      case 'sum': return 'sum(., na.rm = TRUE)';
      case 'mean': return 'mean(., na.rm = TRUE)';
      case 'median': return 'median(., na.rm = TRUE)';
      case 'min': return 'min(., na.rm = TRUE)';
      case 'max': return 'max(., na.rm = TRUE)';
      case 'sd': return 'sd(., na.rm = TRUE)';
      case 'n': return 'sum(!is.na(.))';
      case 'first': return 'dplyr::first(.)';
      case 'last': return 'dplyr::last(.)';
      default: return 'sum(., na.rm = TRUE)';
    }
  },

  styleCall(rule, columnsById, model) {
    const styles = [];
    const text = rule.style.text || {};
    const textArgs = [];

    if (text.color) textArgs.push('color = ' + ExportRgt.str(text.color));
    if (text.size) textArgs.push('size = ' + ExportRgt.size(text.size));
    if (text.weight) textArgs.push('weight = ' + ExportRgt.str(text.weight));
    if (text.style) textArgs.push('style = ' + ExportRgt.str(text.style));
    if (text.align) textArgs.push('align = ' + ExportRgt.str(text.align));
    if (text.vAlign) textArgs.push('v_align = ' + ExportRgt.str(text.vAlign));
    if (text.transform) textArgs.push('transform = ' + ExportRgt.str(text.transform));
    if (text.decorate && text.decorate !== 'none') {
      textArgs.push('decorate = ' + ExportRgt.str(text.decorate === 'line-through' ? 'strikethrough' : text.decorate));
    }
    if (text.stretch) textArgs.push('stretch = ' + ExportRgt.str(text.stretch));
    if (text.whitespace) textArgs.push('whitespace = ' + ExportRgt.str(text.whitespace));
    if (text.indent) textArgs.push('indent = ' + ExportRgt.size(text.indent));
    if (text.font) textArgs.push('font = ' + ExportRgt.fontRef(text.font));

    if (textArgs.length) styles.push('cell_text(' + textArgs.join(', ') + ')');

    if (rule.style.fill && rule.style.fill.color) {
      const fillArgs = ['color = ' + ExportRgt.str(rule.style.fill.color)];
      if (rule.style.fill.alpha !== undefined && rule.style.fill.alpha < 1) {
        fillArgs.push('alpha = ' + rule.style.fill.alpha);
      }
      styles.push('cell_fill(' + fillArgs.join(', ') + ')');
    }

    // gt groups borders by side, so sides sharing a look collapse into one call.
    const borders = rule.style.borders || {};
    const bySignature = new Map();
    for (const side of StyleRules.SIDES) {
      const border = borders[side];
      // `none` is kept, not skipped: since borders gained an `inherit` state,
      // `none` is a rule that says "take the line off these cells", and
      // dropping it here meant that instruction never reached the export.
      if (!border || !border.style) continue;
      const signature = border.style + '|' + border.width + '|' + border.color;
      if (!bySignature.has(signature)) bySignature.set(signature, { border: border, sides: [] });
      bySignature.get(signature).sides.push(side);
    }
    for (const entry of bySignature.values()) {
      const args = ['sides = ' + ExportRgt.strVector(entry.sides),
        'style = ' + ExportRgt.str(ExportRgt.borderStyle(entry.border.style))];
      if (entry.border.style !== 'none') {
        args.push('color = ' + ExportRgt.str(entry.border.color));
        args.push('weight = ' + ExportRgt.size(entry.border.width));
      }
      styles.push('cell_borders(' + args.join(', ') + ')');
    }

    if (!styles.length) return null;

    // A location may resolve to several calls — see `cellRefLocations` — so the
    // list is flattened rather than assumed one-to-one.
    const locations = rule.locations
      .reduce((acc, loc) => acc.concat(ExportRgt.locationCall(loc, columnsById, model) || []), [])
      .filter(Boolean);
    if (!locations.length) return null;

    return 'tab_style(\n' +
      '    style = list(' + styles.join(', ') + '),\n' +
      '    locations = ' + (locations.length === 1 ? locations[0] : 'list(' + locations.join(', ') + ')') + '\n' +
      '  )';
  },

  /** A style rule location as a `cells_*()` call. */
  locationCall(loc, columnsById, model) {
    const args = [];
    const cols = (loc.columns || []).filter((id) => columnsById[id]);

    const rowsArg = () => {
      if (!loc.rows) return null;
      if (loc.rows.mode === 'index' && loc.rows.indices.length) {
        // gt rows are 1-based.
        return 'rows = c(' + loc.rows.indices.map((i) => i + 1).join(', ') + ')';
      }
      if (loc.rows.mode === 'expr' && loc.rows.expr) {
        return 'rows = ' + ExportRgt.translateExpr(loc.rows.expr);
      }
      return null;
    };

    switch (loc.part) {
      case 'body': {
        // An expression naming a neighbouring cell means something different in
        // each column, so it cannot be one `cells_body()`. gt takes a *list* of
        // locations and each may carry its own `rows`, so it becomes one
        // `cells_body()` per column — unrolled here rather than emitted as a
        // loop over `names(data)`, because the column list is known at export
        // time and a pipeline of plain calls is what the rest of this file
        // writes and what a person reading the R expects.
        if (loc.rows && loc.rows.mode === 'expr' && StyleRules.usesCellRefs(loc.rows.expr)) {
          return ExportRgt.cellRefLocations(loc, cols, model);
        }
        if (cols.length) args.push('columns = ' + ExportRgt.columnVector(cols));
        if (rowsArg()) args.push(rowsArg());
        return 'cells_body(' + args.join(', ') + ')';
      }

      case 'stub':
        if (rowsArg()) args.push(rowsArg());
        return 'cells_stub(' + args.join(', ') + ')';

      case 'column_labels':
        if (cols.length) args.push('columns = ' + ExportRgt.columnVector(cols));
        return 'cells_column_labels(' + args.join(', ') + ')';

      case 'column_spanners': {
        // From the model's own spec, not `Store.get()`. This was the one place
        // an exporter reached for global state instead of what it was handed,
        // which made `ExportRgt.build(spec, model)` not a function of its
        // arguments — it would emit the *store's* spanner labels for whatever
        // spec it was given, and throw outright on an empty store.
        const authored = (model && model.spanners) || [];
        // By id, not by label. `cells_column_spanners(spanners = )` matches on
        // gt's spanner id, and a nested pivot repeats labels — so a rule on one
        // year's Q1 was emitted as `spanners = "Q1"` and reached both years'.
        const ids = ExportRgt.spannerIds(authored);
        const spanners = (loc.spanners || [])
          .map((id) => ids[id])
          .filter(Boolean);
        return 'cells_column_spanners(spanners = ' +
          (spanners.length ? ExportRgt.strVector(spanners) : 'everything()') + ')';
      }

      case 'stubhead':
        return 'cells_stubhead()';

      case 'row_groups':
        return 'cells_row_groups(' +
          ((loc.groups || []).length ? 'groups = ' + ExportRgt.strVector(loc.groups) : '') + ')';

      // gt raises "Failed to style the summary of the table" when a location
      // names summary rows the table does not have, and it is the only pair of
      // locations that does — `cells_stub()`, `cells_row_groups()` and
      // `cells_column_spanners()` are all quietly ignored on a table without
      // them. A theme carries part-level rules for parts any given table may
      // not have, so this is reached by applying a theme, not by anything
      // unusual.
      case 'summary':
        if (!(model && model.rows && model.rows.some((r) => r.kind === 'summary'))) return null;
        return ExportRgt.summaryLocation(loc, columnsById, 'summary');

      case 'grand_summary':
        if (!(model && model.rows && model.rows.some((r) => r.kind === 'grand'))) return null;
        return ExportRgt.summaryLocation(loc, columnsById, 'grand_summary');

      case 'title':
        return 'cells_title(groups = "title")';

      case 'subtitle':
        return 'cells_title(groups = "subtitle")';

      case 'footnotes':
        return 'cells_footnotes()';

      case 'source_notes':
        return 'cells_source_notes()';

      default:
        return null;
    }
  },

  /** A footnote location, which uses the same helpers. */
  location(loc, columnsById, model) {
    if (!loc || !loc.part) return null;
    return ExportRgt.locationCall({
      part: loc.part,
      columns: loc.colId ? [loc.colId] : [],
      rows: loc.srcIndex !== undefined ? { mode: 'index', indices: [loc.srcIndex] } : null,
      groups: loc.groupId ? [loc.groupId] : [],
      spanners: loc.spannerId ? [loc.spannerId] : []
    }, columnsById, model);
  },

  /**
   * Translate a row expression from JavaScript to R.
   *
   * Only the common operators are handled — enough for the conditions people
   * actually write. Anything unrecognised is passed through with a comment so
   * the R is at least reviewable rather than silently wrong.
   */
  translateExpr(expr) {
    const translated = String(expr)
      // `v['x']` is how the app reaches a column whose id is not a bare name —
      // `StyleRules.ref` emits it, and every seeded expression uses it for a
      // reserved or non-identifier id. There is no `v` in a `dplyr` mask, so
      // this reached R as "object 'v' not found" and killed the whole script.
      .replace(/\bv\s*\[\s*(['"])((?:\\.|(?!\1)[^\\])*)\1\s*\]/g,
        (whole, quote, id) => ExportRgt.symbol(id.replace(/\\(.)/g, '$1')))
      .replace(/&&/g, '&')
      .replace(/\|\|/g, '|')
      .replace(/===/g, '==')
      .replace(/!==/g, '!=')
      .replace(/\bnull\b/g, 'NA')
      .replace(/\btrue\b/g, 'TRUE')
      .replace(/\bfalse\b/g, 'FALSE')
      .replace(/Math\.abs\(/g, 'abs(')
      .replace(/Math\.max\(/g, 'max(')
      .replace(/Math\.min\(/g, 'min(')
      .replace(/"/g, '"');

    return translated;
  },

  /* ================================================================
     Literals
     ================================================================ */

  /**
   * R's reserved words. A column called `if` or `function` is spelled like an
   * identifier and cannot be used as one, exactly as `n` cannot be a bare name
   * in a row expression — see `StyleRules.RESERVED`, which is this same idea on
   * the JavaScript side.
   */
  R_RESERVED: ['if', 'else', 'repeat', 'while', 'function', 'for', 'next', 'break',
    'TRUE', 'FALSE', 'NULL', 'Inf', 'NaN', 'NA', 'NA_integer_', 'NA_real_',
    'NA_character_', 'in'],

  /** An R symbol, backtick-quoted when the id is not syntactic. */
  symbol(id) {
    const syntactic = /^[A-Za-z.][A-Za-z0-9._]*$/.test(id) &&
      !/^\.\d/.test(id) &&
      ExportRgt.R_RESERVED.indexOf(String(id)) < 0;
    return syntactic ? id : '`' + id + '`';
  },

  /** A column reference as a quoted name, for `rowname_col` and friends. */
  name(id) {
    return '"' + String(id).replace(/"/g, '\\"') + '"';
  },

  /** `c(a, b, c)` of bare column symbols. */
  /**
   * One `cells_body()` per column, for a `where` expression naming neighbours.
   *
   * `self()`, `above(k)` and `below(k)` are about the column being styled, so
   * they resolve against it: the column itself, `dplyr::lag()` and
   * `dplyr::lead()`. `left(k)` and `right(k)` are about a different column, so
   * they resolve to that column's name — which is why this has to be unrolled
   * per column in the first place.
   *
   * Both boundaries come out right without being special-cased. `lag()` yields
   * `NA` at the top and gt drops an `NA` row from a `rows =` predicate, which
   * is what `undefined` does to a comparison in the preview. A column with no
   * neighbour to its left simply emits no call, because no cell in it can
   * match — which is what an empty set means in the preview too.
   *
   * @returns {string[]} location calls, possibly empty
   */
  cellRefLocations(loc, cols, model) {
    const body = Compute.bodyColumnIds(model || {});
    const targets = cols.length ? cols : body;
    const out = [];

    for (const colId of targets) {
      const index = body.indexOf(colId);
      let impossible = false;

      const sideways = (offset) => {
        const neighbour = index < 0 ? undefined : body[index + offset];
        if (neighbour === undefined) { impossible = true; return 'NA'; }
        return ExportRgt.symbol(neighbour);
      };
      const step = (raw) => {
        const k = raw === undefined || String(raw).trim() === '' ? 1 : Math.trunc(Number(raw));
        return isFinite(k) ? k : 1;
      };

      const resolved = String(loc.rows.expr)
        .replace(/\bself\s*\(\s*\)/g, () => ExportRgt.symbol(colId))
        .replace(/\babove\s*\(\s*([^)]*)\s*\)/g,
          (whole, k) => 'lag(' + ExportRgt.symbol(colId) + ', ' + step(k) + ')')
        .replace(/\bbelow\s*\(\s*([^)]*)\s*\)/g,
          (whole, k) => 'lead(' + ExportRgt.symbol(colId) + ', ' + step(k) + ')')
        .replace(/\bleft\s*\(\s*([^)]*)\s*\)/g, (whole, k) => sideways(-step(k)))
        .replace(/\bright\s*\(\s*([^)]*)\s*\)/g, (whole, k) => sideways(step(k)));

      if (impossible) continue;
      out.push('cells_body(columns = ' + ExportRgt.symbol(colId) +
        ', rows = ' + ExportRgt.translateExpr(resolved) + ')');
    }

    return out;
  },

  /**
   * `cells_summary()` / `cells_grand_summary()` for a location.
   *
   * gt's `cells_summary()` also takes `groups =`, and the preview anchors a
   * summary footnote to one group only — `Compute.locationKey` treats `groups`
   * as part of a summary row's identity. Without it the export styled or
   * footnoted every group's summary row, disagreeing with the preview. A grand
   * summary spans every group and carries none.
   */
  summaryLocation(loc, columnsById, part) {
    const args = [];
    const cols = (loc.columns || []).filter((id) => columnsById[id]);
    if (cols.length) args.push('columns = ' + ExportRgt.columnVector(cols));
    if (part === 'summary' && (loc.groups || []).length) {
      args.push('groups = ' + ExportRgt.strVector(loc.groups));
    }
    const fn = part === 'summary' ? 'cells_summary' : 'cells_grand_summary';
    return fn + '(' + args.join(', ') + ')';
  },

  /**
   * A CSS border style as gt's `cell_borders()` spells it.
   *
   * gt takes solid / dashed / dotted / hidden / double and rejects anything
   * else, including `none` — which is the app's word for the same thing, and
   * the one a rule uses to take a line off. Everything else is spelled alike.
   */
  borderStyle(style) {
    return String(style) === 'none' ? 'hidden' : String(style);
  },

  /**
   * The `tab_style()` calls standing in for options gt has no argument for.
   *
   * `column_labels.spanner.*` and `row_group.font.style` are real options here
   * — the preview draws them, themes set them — and `tab_options()` has no
   * counterpart. gt's own way of saying these is `tab_style()`, which is also
   * how `opt_stylize()` gives gt a coloured header, so this is the same route
   * the themes' own part-level rules already take.
   *
   * Only what differs from the default is emitted, so an untouched table still
   * exports a bare `gt()` pipeline.
   */
  optionStyleCalls(options) {
    const changed = OptionsSchema.diff(options);
    const out = [];
    const at = (key) => (changed[key] === undefined ? OptionsSchema.get(key).default : changed[key]);

    const spannerKeys = ['column_labels.spanner.border.bottom.style',
      'column_labels.spanner.border.bottom.width',
      'column_labels.spanner.border.bottom.color',
      'column_labels.spanner.underline'];

    if (changed['table.font.names'] !== undefined) {
      out.push('opt_table_font(font = ' + ExportRgt.fontRef(changed['table.font.names']) + ')');
    }

    if (spannerKeys.some((key) => changed[key] !== undefined)) {
      // The underline switch and the border triplet are one line on screen: the
      // switch decides whether it is drawn, the triplet what it looks like.
      const style = at('column_labels.spanner.underline')
        ? at('column_labels.spanner.border.bottom.style')
        : 'none';
      const parts = ['sides = "bottom"', 'style = ' + ExportRgt.str(ExportRgt.borderStyle(style))];
      if (style !== 'none') {
        parts.push('weight = ' + ExportRgt.optionValue('column_labels.spanner.border.bottom.width',
          at('column_labels.spanner.border.bottom.width')));
        parts.push('color = ' + ExportRgt.str(at('column_labels.spanner.border.bottom.color')));
      }
      out.push('tab_style(style = list(cell_borders(' + parts.join(', ') + ')), ' +
        'locations = cells_column_spanners())');
    }

    if (changed['row_group.font.style'] !== undefined) {
      out.push('tab_style(style = list(cell_text(style = ' +
        ExportRgt.str(at('row_group.font.style')) + ')), locations = cells_row_groups())');
    }

    return out;
  },

  /**
   * `dplyr::arrange()` for the spec's sort keys, or null when there are none.
   *
   * The keys have to produce gt's order, not merely a plausible one, so each
   * one is emitted as the same comparison `Compute.sortRows` makes:
   *
   *   number   the column itself. `arrange()` puts NA last whichever direction
   *            is asked for, which is what the preview does.
   *   text     `stringr::str_rank(x, numeric = TRUE)`, which reproduces
   *            `localeCompare(…, {numeric: true, sensitivity: 'base'})` — case
   *            folded, and "Study 2" before "Study 10". Plain `arrange()` on a
   *            character column is neither: it gives STUDY 20, Study 1,
   *            Study 10, study 2.
   *
   * Fully qualified rather than adding `library(stringr)` to the preamble, so
   * a table with no text sort carries no dependency it does not use.
   */
  sortCall(sort, columnsById) {
    const keys = (sort || []).filter((key) => columnsById[key.col]);
    if (!keys.length) return null;

    const terms = keys.map((key) => {
      const column = columnsById[key.col];
      const symbol = ExportRgt.symbol(key.col);
      const term = column.type === 'number'
        ? symbol
        : 'stringr::str_rank(' + symbol + ', numeric = TRUE)';
      return key.dir === 'desc' ? 'desc(' + term + ')' : term;
    });

    return 'dplyr::arrange(' + terms.join(', ') + ')';
  },

  /**
   * A readable, unique gt id for every spanner in the spec.
   *
   * gt identifies a spanner by `id`, defaulting it to the label and requiring
   * uniqueness — but a nested pivot repeats its inner labels by construction,
   * so the label cannot serve. The slug of the label leads because that is what
   * a person reading the R will recognise; a repeat takes a numeric suffix, and
   * a label that slugs to nothing falls back to the spec's own id.
   *
   * **One producer**, because two things need the same answer: the
   * `tab_spanner()` call that declares the id and the
   * `cells_column_spanners()` that refers to it.
   */
  spannerIds(spanners) {
    const out = {};
    const used = new Set();
    for (const spanner of spanners || []) {
      const base = Util.slug(String(spanner.label || '')) || String(spanner.id);
      let id = base;
      let n = 2;
      while (used.has(id)) { id = base + '_' + n; n += 1; }
      used.add(id);
      out[spanner.id] = id;
    }
    return out;
  },

  /**
   * A number as R source. `1e21` would otherwise stringify to "1e+21", which R
   * reads fine, but `Infinity` and `NaN` do not exist as R literals — a domain
   * can reach either from a column of one repeated value.
   */
  rNumber(value) {
    if (value === null || value === undefined || !isFinite(value)) return 'NA';
    return String(value);
  },

  columnVector(ids) {
    if (ids.length === 1) return ExportRgt.symbol(ids[0]);
    return 'c(' + ids.map(ExportRgt.symbol).join(', ') + ')';
  },

  str(value) {
    return '"' + String(value === null || value === undefined ? '' : value)
      .replace(/\\/g, '\\\\')
      .replace(/"/g, '\\"')
      .replace(/\n/g, '\\n') + '"';
  },

  strVector(values) {
    if (values.length === 1) return ExportRgt.str(values[0]);
    return 'c(' + values.map(ExportRgt.str).join(', ') + ')';
  },

  /** Text carrying markup becomes `md()`, so gt renders it too. */
  md(text) {
    const str = String(text === null || text === undefined ? '' : text);
    if (!Markup.hasMarkup(str)) return ExportRgt.str(str);

    // This app's markup is close enough to Markdown for bold and italic; the
    // sup/sub forms need HTML, so those go through html().
    if (/\^\{|_\{|\^\S|_\S/.test(str)) {
      return 'html(' + ExportRgt.str(Markup.toHtml(str)) + ')';
    }
    return 'md(' + ExportRgt.str(str) + ')';
  },

  /** A CSS length as gt's `px()` or `pct()` helper. */
  width(value) {
    const str = String(value);
    if (str.indexOf('%') >= 0) return 'pct(' + parseFloat(str) + ')';
    const num = Util.cssNumber(str);
    return num === null ? ExportRgt.str(str) : 'px(' + num + ')';
  },

  size(value) {
    const str = String(value);
    if (str.indexOf('%') >= 0 || str.indexOf('em') >= 0) return ExportRgt.str(str);
    const num = Util.cssNumber(str);
    return num === null ? ExportRgt.str(str) : 'px(' + num + ')';
  },

  /**
   * A font reference as gt sees it.
   *
   * Google families map onto `google_font()`. An uploaded face has no gt
   * equivalent — gt cannot inline a binary — so it is named and left to the R
   * session to have installed, with the fallback stack behind it.
   */
  fontRef(id) {
    const family = Fonts.webFamily(id);
    if (family) return 'google_font(name = ' + ExportRgt.str(family) + ')';

    const local = Fonts.embedded(id);
    if (local) return ExportRgt.str(Fonts.stack(id));

    return ExportRgt.str(Fonts.stack(id));
  },

  /**
   * The gt `tab_options()` argument for a schema key.
   *
   * They are the same string. **The schema's keys are gt's argument names**,
   * dots and all — that is why they look the way they do — and this used to
   * replace every dot with an underscore, producing `table_font_names` for
   * gt's `table.font.names`. `tab_options()` has no `...`, so one unknown name
   * fails the call and the whole script with it: **every theme in the app
   * exported R that would not run**, and the only reason it was not obvious is
   * that a table with no options changed emits no `tab_options()` at all.
   *
   * Kept as a function rather than inlined, because it is the place to notice
   * if the two ever stop being the same string.
   */
  optionName(key) {
    return key;
  },

  optionValue(key, value) {
    const option = OptionsSchema.get(key);
    if (!option) return ExportRgt.str(value);

    if (option.type === 'bool') return value ? 'TRUE' : 'FALSE';
    if (option.type === 'fonts') return ExportRgt.fontRef(value);
    if (option.type === 'len') {
      const str = String(value);
      if (str === 'auto' || str.indexOf('%') >= 0 || str.indexOf('em') >= 0) return ExportRgt.str(str);
      const num = Util.cssNumber(str);
      return num === null ? ExportRgt.str(str) : 'px(' + num + ')';
    }
    if (option.type === 'color' && !value) return 'NA';

    return ExportRgt.str(value);
  },

  /** One data value as an R literal. */
  value(raw, type) {
    if (Util.isMissing(raw)) return 'NA';
    if (type === 'number') {
      const num = Util.toNumber(raw);
      return num === null ? ExportRgt.str(raw) : String(num);
    }
    if (type === 'bool') {
      return /^(true|yes|t)$/i.test(String(raw).trim()) ? 'TRUE' : 'FALSE';
    }
    return ExportRgt.str(raw);
  }
};
